import { VerticalBox, ProgressIndicator, HorizontalBox } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "Piton | System Monitor";
    width: 400px;
    height: 200px;

    in property <float> swap_load;
    in property <float> ram_load;

    in property <string> system_name; 
    in property <string> kernel_version;

    VerticalBox {
        HorizontalBox {
            Text {
                text: "\{root.system_name}";
                font-size: 20px;
            }

            Rectangle {}

            Text {
                text: "\{root.kernel_version}";
                font-size: 20px;
            }
        }

        Text {
            text: "Swap: \{round(root.swap_load * 100)}%";
            font-size: 16px;
        }
        ProgressIndicator {
            progress: root.swap_load;
        }
    
        Text {
            text: "RAM: \{round(root.ram_load * 100)}%";
            font-size: 16px;
        }
        ProgressIndicator {
            progress: root.ram_load;
        }
    }
}